FROM alpine:3.19

RUN apk add --no-cache bash build-base cmake openssl-dev libssh2-dev libssh2-static openssl-libs-static

WORKDIR /nativebinaries
COPY . /nativebinaries/

CMD ["/bin/bash", "-c", "./build.libgit2.sh"]
